TOPOSTGFORMER_INRIX_MANHATTAN:
  num_nodes: 1212
  in_steps: 12
  out_steps: 6

  train_size: 0.6
  val_size: 0.2

  time_of_day: False
  day_of_week: False

  lr: 0.001
  weight_decay: 0.005
  milestones: [20, 40, 60, 80, 100, 120, 140, 160, 180]
  warmup_epochs: 3
  lr_decay_rate: 0.25
  batch_size: 16
  max_epochs: 300
  early_stop: 30
  use_cl: False
  cl_step_size: 2500
  motifs: ['3-stars', '4-stars', '4-cycles']


  model_args:
    num_nodes: 1212
    in_steps: 12
    out_steps: 6
    steps_per_day: 288
    input_dim: 1
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 0
    dow_embedding_dim: 0
    adaptive_embedding_dim: 12
    kernel_size: [1, 1, 1]
    order: 1
    num_heads: 4
    num_layers: 6
    dropout: 0.1
    dropout_a: 0.35